# Ruta: backend/app/contexts/products/domain/repositories.py

from abc import ABC, abstractmethod
from typing import Optional

from app.contexts.products.domain.entities import Category, Product, Supplier


class ProductRepository(ABC):
    @abstractmethod
    def find_by_id(self, product_id: int) -> Optional[Product]: ...
    @abstractmethod
    def find_by_code(self, code: str) -> Optional[Product]: ...
    @abstractmethod
    def find_all(self, active_only: bool = True) -> list[Product]: ...
    @abstractmethod
    def save(self, product: Product) -> Product: ...
    @abstractmethod
    def update(self, product: Product) -> Product: ...
    @abstractmethod
    def delete(self, product_id: int) -> None: ...


class CategoryRepository(ABC):
    @abstractmethod
    def find_by_id(self, category_id: int) -> Optional[Category]: ...
    @abstractmethod
    def find_all(self) -> list[Category]: ...
    @abstractmethod
    def save(self, category: Category) -> Category: ...
    @abstractmethod
    def update(self, category: Category) -> Category: ...


class SupplierRepository(ABC):
    @abstractmethod
    def find_by_id(self, supplier_id: int) -> Optional[Supplier]: ...
    @abstractmethod
    def find_all(self) -> list[Supplier]: ...
    @abstractmethod
    def save(self, supplier: Supplier) -> Supplier: ...